import Placeholder from "react-bootstrap/Placeholder";
import Container from "react-bootstrap/Container";
import Form from "@/components/sales/Form";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import { GetServerSideProps, GetServerSidePropsContext } from "next";
import { getSession } from "next-auth/react";
import { User } from "@/types/User";
import { useEffect, useState } from "react";

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  try {
    const { req } = context;
    const session = await getSession({ req: req });

    if (!session) {
      return {
        props: {},
        redirect: {
          destination: "/",
        },
      };
    }

    return {
      props: { user: session.user },
    };
  } catch (error) {
    return {
      props: {},
    };
  }
};

export default function Dashboard({ user }: { user: User }) {
  const [loading, setLoading] = useState(true);

  useEffect(() => setLoading(false), []);

  return (
    <Container className="bg-white p-4 rounded">
      <p className="fs-5 lh-1 my-1">
        {loading && (
          <Placeholder animation="glow">
            <Placeholder xs={2} style={{ borderRadius: 5 }} bg="dark" />
          </Placeholder>
        )}
        {!loading && <strong>Sales Report</strong>}
      </p>
      <Row className="mb-3 mt-4">
        <Col md={6} sm={12}>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Total Revenue:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading &&
              "The total amount of money generated by all transactions."}
          </p>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Number of Transaction:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading && "The total number of transaction processed."}
          </p>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Average Transaction:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading && "The average amount of money spent per transaction."}
          </p>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Top 10 selling donuts:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading &&
              "The list of the best selling donuts, sorted by revenue and quantity sold."}
          </p>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Customer Information:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading && "Number of new customers and top 10 customers."}
          </p>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Inventory Information:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading &&
              "The breakdown of donut quantity sold, popular donut, and low quantity donuts."}
          </p>
          <p>
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={2}
                  className="me-2"
                  style={{ borderRadius: 5 }}
                  bg="dark"
                />
              </Placeholder>
            )}
            {!loading && <strong>Cashier Transaction:</strong>}
            {loading && (
              <Placeholder animation="glow">
                <Placeholder
                  xs={8}
                  style={{ borderRadius: 5 }}
                  bg="secondary"
                />
              </Placeholder>
            )}
            {!loading &&
              "The total number of transaction processed by cashier."}
          </p>
        </Col>
        <Col md={6} sm={12}>
          {loading && (
            <Placeholder animation="glow">
              <Placeholder
                xs={5}
                className="mb-3"
                style={{ borderRadius: 5, height: 25 }}
                bg="dark"
              />
            </Placeholder>
          )}
          {!loading && <h2>Generate Report:</h2>}
          <Form userRole={user.role} pageLoading={loading} />
        </Col>
      </Row>
    </Container>
  );
}
