import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import { Container } from "react-bootstrap";
import Form from "@/components/sales/Form";

import { GetServerSideProps, GetServerSidePropsContext } from "next";
import { getSession } from "next-auth/react";

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  try {
    const { req } = context;
    const session = await getSession({ req: req });

    if (!session) {
      return {
        props: {},
        redirect: {
          destination: "/",
        },
      };
    }

    return {
      props: { user: session.user },
    };
  } catch (error) {
    return {
      props: {},
    };
  }
};

export default function Dashboard({ user }: { user: Record<string, any> }) {
  return (
    <Container className="bg-white p-4 rounded">
      <p className="fs-5 lh-1 my-1">
        <strong>Sales Report</strong>
      </p>
      <Row className="mb-3 mt-4">
        <Col>
          <h3>Report Contents:</h3>
          <p>
            <strong>• Total Revenue</strong> - The total amount of money
            generated by all transactions.
          </p>
          <p>
            <strong>• Number of Transaction</strong> - The total number of
            transaction processed.
          </p>
          <p>
            <strong>• Average Transaction</strong> - The average amount of money
            spent per transaction.
          </p>
          <p>
            <strong>• Top 10 selling donuts</strong> - The list of the best
            selling donuts, sorted by revenue and quantity sold.
          </p>
          <p>
            <strong>• Customer Information</strong> - Number of new customers
            and top 10 customers.
          </p>
          <p>
            <strong>• Inventory Information</strong> - The breakdown of donut
            quantity sold, popular donut, and low quantity donuts.
          </p>
          <p>
            <strong>• Cashier Transaction</strong> - The total number of
            transaction processed by cashier.
          </p>
        </Col>
        <Col>
          <Form userRole={user.role} />
        </Col>
      </Row>
    </Container>
  );
}
